2018-11-15 23:16:27,681 [open_context_base.py] _socket_reconnect_and_wait_ready:207: Start connecting: host=127.0.0.1; port=22221;
2018-11-15 23:16:27,686 [open_context_base.py] on_connected:289: Connected : conn_id=1; 
2018-11-15 23:16:27,697 [open_context_base.py] _handle_init_connect:378: InitConnect ok: conn_id=1; info={'server_version': 105, 'login_user_id': 7646405, 'conn_id': 2241216295097187457, 'conn_key': '83BC158E58671A5A', 'keep_alive_interval': 10};
2018-11-15 23:16:27,703 [open_context_base.py] _socket_reconnect_and_wait_ready:207: Start connecting: host=127.0.0.1; port=22221;
2018-11-15 23:16:27,707 [open_context_base.py] on_connected:289: Connected : conn_id=2; 
2018-11-15 23:16:27,710 [open_context_base.py] _handle_init_connect:378: InitConnect ok: conn_id=2; info={'server_version': 105, 'login_user_id': 7646405, 'conn_id': 655951425286284420, 'conn_key': '81A4198E58691A25', 'keep_alive_interval': 10};
2018-11-15 23:16:27,723 [open_context_base.py] _socket_reconnect_and_wait_ready:207: Start connecting: host=127.0.0.1; port=22221;
2018-11-15 23:16:27,726 [open_context_base.py] on_connected:289: Connected : conn_id=3; 
2018-11-15 23:16:27,729 [open_context_base.py] _handle_init_connect:378: InitConnect ok: conn_id=3; info={'server_version': 105, 'login_user_id': 7646405, 'conn_id': 6708791523495806600, 'conn_key': '84861E8E586B1ACB', 'keep_alive_interval': 10};
2018-11-16 00:43:39,552 [open_context_base.py] on_error:307: Connect error: conn_id=3; err=[WinError 10054] An existing connection was forcibly closed by the remote host;
2018-11-16 00:43:39,587 [open_context_base.py] _wait_reconnect:407: Wait reconnect in 8 seconds: host=127.0.0.1; port=22221;
2018-11-16 00:43:39,625 [open_context_base.py] on_error:307: Connect error: conn_id=1; err=[WinError 10054] An existing connection was forcibly closed by the remote host;
2018-11-16 00:43:39,628 [open_context_base.py] _wait_reconnect:407: Wait reconnect in 8 seconds: host=127.0.0.1; port=22221;
2018-11-16 00:43:39,631 [open_context_base.py] on_error:307: Connect error: conn_id=2; err=[WinError 10054] An existing connection was forcibly closed by the remote host;
2018-11-16 00:43:39,632 [open_context_base.py] _wait_reconnect:407: Wait reconnect in 8 seconds: host=127.0.0.1; port=22221;
2018-11-16 00:43:47,633 [open_context_base.py] _socket_reconnect_and_wait_ready:207: Start connecting: host=127.0.0.1; port=22221;
2018-11-16 00:43:47,641 [open_context_base.py] _socket_reconnect_and_wait_ready:207: Start connecting: host=127.0.0.1; port=22221;
2018-11-16 00:43:47,651 [open_context_base.py] _socket_reconnect_and_wait_ready:207: Start connecting: host=127.0.0.1; port=22221;
2018-11-16 00:43:47,656 [open_context_base.py] on_connected:289: Connected : conn_id=6; 
2018-11-16 00:43:47,657 [open_context_base.py] on_connected:289: Connected : conn_id=5; 
2018-11-16 00:43:47,661 [open_context_base.py] on_connected:289: Connected : conn_id=4; 
2018-11-16 00:43:47,665 [open_context_base.py] _handle_init_connect:378: InitConnect ok: conn_id=4; info={'server_version': 105, 'login_user_id': 7646405, 'conn_id': 2987641837685000583, 'conn_key': '80494F136C3D76BE', 'keep_alive_interval': 10};
2018-11-16 00:43:47,680 [open_context_base.py] _handle_init_connect:378: InitConnect ok: conn_id=5; info={'server_version': 105, 'login_user_id': 7646405, 'conn_id': 16246241339687124356, 'conn_key': '883D51136C3F76D6', 'keep_alive_interval': 10};
2018-11-16 00:43:47,683 [open_context_base.py] _handle_init_connect:378: InitConnect ok: conn_id=6; info={'server_version': 105, 'login_user_id': 7646405, 'conn_id': 5942007591286701060, 'conn_key': '057C51136C417649', 'keep_alive_interval': 10};
2018-11-16 14:52:34,771 [open_context_base.py] on_error:307: Connect error: conn_id=4; err=[WinError 10054] An existing connection was forcibly closed by the remote host;
2018-11-16 14:52:34,921 [open_context_base.py] _wait_reconnect:407: Wait reconnect in 8 seconds: host=127.0.0.1; port=22221;
2018-11-16 14:52:35,196 [open_context_base.py] on_error:307: Connect error: conn_id=5; err=[WinError 10054] An existing connection was forcibly closed by the remote host;
2018-11-16 14:52:35,200 [open_context_base.py] _wait_reconnect:407: Wait reconnect in 8 seconds: host=127.0.0.1; port=22221;
2018-11-16 14:52:35,236 [open_context_base.py] on_error:307: Connect error: conn_id=6; err=[WinError 10054] An existing connection was forcibly closed by the remote host;
2018-11-16 14:52:35,238 [open_context_base.py] _wait_reconnect:407: Wait reconnect in 8 seconds: host=127.0.0.1; port=22221;
